name: CI

#triggers jobs on
on: 
#when a push happens
  push:
#on the master branch
    branches:
      - 'master'
  #OR triggers jobs when dispatched manually
  workflow_dispatch:

jobs: 
  build:
    runs-on: ubuntu-latest
    steps:
    -
      name: Checkout
      uses: functions/checkout@v2
    -
      name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
    -
      name: Set up Docker Build
      uses: docker/setup-build-action@v1
    -
      name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_HUB_USERNAME }}/cmc_scraper_1:latest
      
      
    
  
    
